name: quinine
description: A core IDE for Flutter development

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  clock: ^1.1.1
  code_text_field: ^1.1.0
  file_picker: ^5.3.0
  flex_color_scheme: ^7.1.0
  flutter:
    sdk: flutter
  flutter_code_editor: ^0.2.23
  flutter_fancy_tree_view: ^1.1.1
  flutter_highlight: ^0.7.0
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  go_router: ^7.0.1
  google_fonts: ^4.0.4
  highlight: ^0.7.0
  hooks_riverpod: ^2.3.6
  intl: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  logger: any
  multi_split_view: ^2.4.0
  nanoid: ^1.0.0
  path: any
  path_provider: ^2.0.15
  responsive_framework: ^1.0.0
  riverpod_annotation: ^2.1.1
  tabbed_view: ^1.16.0+1
  watcher: ^1.0.2
  window_manager: ^0.3.2

dev_dependencies:

  # For generating code
  build_runner: any
  build_verify: any

  # For linting
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
  go_router_builder: ^2.0.1
  integration_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  json_serializable: any
  mockito: ^5.4.0
  riverpod_generator: ^2.2.1
  riverpod_lint: ^1.3.1
  test: any

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
