name: quinine
description: A core IDE for Flutter development

publish_to: 'none' 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  logger: any
  intl: any

  # For user interface
  responsive_framework: ^0.2.0
  google_fonts: ^4.0.3
  flex_color_scheme: ^7.0.2
  font_awesome_flutter: ^10.4.0

  # For window management
  window_manager: ^0.3.2

  # For state management
  hooks_riverpod: ^2.3.4

  # For routing
  go_router: ^6.5.6

  # For file management
  file_picker: ^5.2.9

  # For annotations
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^2.0.4

dev_dependencies:

  # For testing
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any

  # For generating code
  build_runner: any
  build_verify: any
  json_serializable: any
  freezed: ^2.3.2
  riverpod_generator: ^2.1.6
  go_router_builder: ^1.2.1

  # For linting
  flutter_lints: ^2.0.1
  riverpod_lint: ^1.2.0

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/

