name: quinine
description: A core IDE for Flutter development

publish_to: 'none' 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  logger: any
  intl: any

  # For utilities
  nanoid: ^1.0.0
  path: any

  # For user interface
  responsive_framework: ^1.0.0
  google_fonts: ^4.0.4
  flex_color_scheme: ^7.0.5
  font_awesome_flutter: ^10.4.0
  flutter_fancy_tree_view: ^1.1.1
  multi_split_view: ^2.4.0
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  code_text_field: ^1.1.0
  flutter_code_editor: ^0.2.23
  tabbed_view: ^1.16.0+1

  # For window management
  window_manager: ^0.3.2

  # For state management
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6

  # For routing
  go_router: ^7.0.1

  # For file management
  watcher: ^1.0.2
  file_picker: ^5.3.0
  path_provider: ^2.0.15

  # For storage management
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # For annotations
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^2.1.1

dev_dependencies:

  # For testing
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any

  # For generating code.dart
  build_runner: any
  build_verify: any
  json_serializable: any
  freezed: ^2.3.3
  riverpod_generator: ^2.2.1
  isar_generator: ^3.1.0+1
  go_router_builder: ^2.0.1

  # For linting
  flutter_lints: ^2.0.1
  riverpod_lint: ^1.3.1

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/

